FROM golang:1.17-alpine AS build

RUN apk add --no-cache git
WORKDIR /tmp/api 
ENV GO111MODULE=auto
COPY . .
RUN ls -la
# RUN go get -d -v ./...
RUN go build -o ./out/api cmd/api/main.go


FROM alpine:3.10.3
RUN apk add ca-certificates
COPY --from=build /tmp/api/out/api /app/api
CMD ["/app/api"]